apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-node-deployment
  labels:
    app: manager-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-node
  template:
    metadata:
      labels:
        app: manager-node
    spec:
      containers:
      - name: manager-node
        image: gaella818/manager-node:0.1.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: manager-node-service
spec:
  selector:
    app: manager-node
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30000
